# Generated by Django 5.2.4 on 2025-08-12 19:11

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Durum')),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
                ('unit', models.CharField(choices=[('count', 'Adet')], default='count', max_length=20)),
                ('reset_policy', models.CharField(choices=[('never', 'Sıfırlanmaz'), ('yearly', 'Yıllık'), ('monthly', 'Aylık'), ('daily', 'Günlük')], default='never', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Özellikler',
                'ordering': ['alignment'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Durum')),
                ('price', models.SmallIntegerField(default=0, verbose_name='Ücret')),
                ('billing_style', models.CharField(choices=[('aylik', 'Aylık'), ('yillik', 'Yıllık')], default='aylik', max_length=20, verbose_name='Ödeme Tipi')),
            ],
            options={
                'verbose_name_plural': 'Planlar',
                'ordering': ['alignment'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizasyonlar',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('canceled', 'İptal')], default='active', max_length=20, verbose_name='Durum')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pricing.organization', verbose_name='Organizasyon')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name_plural': 'Abonelikler',
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Periyot Başlangıcı')),
                ('period_end', models.DateTimeField(verbose_name='Periyot Bitişi')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.features', verbose_name='Özellik')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='pricing.subscription', verbose_name='Abonelik')),
            ],
            options={
                'verbose_name_plural': 'Özellik Kullanımları',
            },
        ),
        migrations.CreateModel(
            name='FeaturesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.features')),
            ],
            options={
                'verbose_name': 'features Translation',
                'db_table': 'pricing_features_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limit')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_plans', to='pricing.features', verbose_name='Özellik')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='pricing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name_plural': 'Plan Özellikleri',
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.plan')),
            ],
            options={
                'verbose_name': 'plan Translation',
                'db_table': 'pricing_plan_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='pricing_sub_organiz_e7a82b_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['subscription', 'feature', 'period_start', 'period_end'], name='pricing_fea_subscri_01068d_idx'),
        ),
    ]
