# Generated by Django 5.2.4 on 2025-08-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_company', to='company.company', verbose_name='Şirket'),
            preserve_default=False,
        ),
    ]
