# Generated by Django 5.2.4 on 2025-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_remove_organization_owner_organization_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
