# Generated by Django 5.2.4 on 2025-08-03 13:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
            ],
            options={
                'verbose_name_plural': 'Sıkça Sorulan Sorular',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='img/site_settings', verbose_name='Logo')),
                ('shortcut', models.FileField(upload_to='img/site_settings', verbose_name='İkon')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.CharField(max_length=100, verbose_name='Mail')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('google_maps_link', models.CharField(max_length=1000, verbose_name='Google Maps Link')),
            ],
            options={
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='web/sliders', verbose_name='Resim')),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
                ('has_redirect', models.BooleanField(default=False, verbose_name='Yönlendirme var mı?')),
            ],
            options={
                'verbose_name_plural': 'Sliderlar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='web/header/nav/menu_items', verbose_name='İkon')),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
                ('link', models.CharField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Alt Menüler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('sub_menu', models.ManyToManyField(blank=True, related_name='menu_items', to='web.submenu', verbose_name='Alt Menüler')),
            ],
            options={
                'verbose_name_plural': 'Menüler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=300, verbose_name='Soru')),
                ('answer', models.CharField(max_length=2000, verbose_name='Cevap')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.faq')),
            ],
            options={
                'verbose_name': 'faq Translation',
                'db_table': 'web_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='İsim')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.menuitem')),
            ],
            options={
                'verbose_name': 'menu item Translation',
                'db_table': 'web_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SlidersTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=500, verbose_name='Yazı')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Text')),
                ('link', models.CharField(blank=True, null=True, verbose_name='Link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.sliders')),
            ],
            options={
                'verbose_name': 'sliders Translation',
                'db_table': 'web_sliders_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubMenuTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='İsim')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.submenu')),
            ],
            options={
                'verbose_name': 'sub menu Translation',
                'db_table': 'web_submenu_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
