# Generated by Django 5.2.4 on 2025-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link',
        ),
        migrations.AddField(
            model_name='menuitemtranslation',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
    ]
