# Generated by Django 5.2.4 on 2025-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_menuitem_link_menuitemtranslation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayınlansın mı?'),
        ),
    ]
