# Generated by Django 5.2.4 on 2025-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sliders_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='image_alignment',
            field=models.CharField(choices=[('left', 'Sol'), ('right', 'Sağ')], default='left', max_length=10, verbose_name='Resim Konumu'),
            preserve_default=False,
        ),
    ]
