# Generated by Django 5.2.4 on 2025-08-03 19:26

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sliders_image_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('icon', models.FileField(upload_to='web/why_use/icons')),
                ('alignment', models.SmallIntegerField(default=1, verbose_name='Sıra')),
            ],
            options={
                'verbose_name_plural': 'Neden Kullanmalıyız?',
                'ordering': ['alignment'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['alignment'], 'verbose_name_plural': 'Sıkça Sorulan Sorular'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['alignment'], 'verbose_name_plural': 'Menüler'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['alignment'], 'verbose_name_plural': 'Alt Menüler'},
        ),
        migrations.CreateModel(
            name='WhyUseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(max_length=500, verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web.whyuse')),
            ],
            options={
                'verbose_name': 'why use Translation',
                'db_table': 'web_whyuse_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
