# Generated by Django 5.2.4 on 2025-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_features_featurestranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestranslation',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Açıklama'),
            preserve_default=False,
        ),
    ]
