# Generated by Django 5.2.4 on 2025-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_contentblock_contentblocktranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name_plural': 'İçerik Bloğu'},
        ),
    ]
