# Generated by Django 5.2.4 on 2025-08-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_sitesettings_alter_contentblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.SmallIntegerField(verbose_name='Ülke ID')),
                ('iso2', models.CharField(max_length=2)),
                ('emoji', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Ülkeler',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='web.country')),
            ],
            options={
                'verbose_name_plural': 'Şehirler',
            },
        ),
    ]
