# Generated by Django 5.2.4 on 2025-08-09 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_country_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderstranslation',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Metin'),
        ),
    ]
