# Generated by Django 5.2.4 on 2025-08-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_sliderstranslation_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={'ordering': ['alignment'], 'verbose_name_plural': 'Sliderlar'},
        ),
    ]
