# Generated by Django 5.2.4 on 2025-08-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0010_country_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('phone', models.BigIntegerField(verbose_name='Telefon')),
                ('company_name', models.CharField(max_length=300, verbose_name='Şirket İsmi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.city', verbose_name='Şehir')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ülke', to='web.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
