# Generated by Django 5.2.4 on 2025-08-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_activityarea_id_remove_company_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityArea',
        ),
        migrations.DeleteModel(
            name='ActivityAreaTranslation',
        ),
        migrations.DeleteModel(
            name='CompanyTranslation',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.DeleteModel(
            name='FacilitiesTranslation',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='SectorTranslation',
        ),
    ]
