# Generated by Django 5.2.4 on 2025-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portal/company/logo', verbose_name='Logo'),
        ),
    ]
