# Generated by Django 5.2.4 on 2025-08-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_logo'),
        ('web', '0012_alter_sliders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='web.country', verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_country', to='web.country', verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_no',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
