# Generated by Django 5.2.4 on 2025-08-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_city_company_country_company_phone_and_more'),
        ('web', '0012_alter_sliders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='web.city', verbose_name='Şehir'),
        ),
    ]
