# Generated by Django 5.2.4 on 2025-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
