# Generated by Django 5.2.4 on 2025-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='personnel_count',
            field=models.SmallIntegerField(default=0, verbose_name='Personel Sayısı'),
        ),
    ]
