# Generated by Django 5.2.4 on 2025-08-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_personnel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='building_count',
            field=models.SmallIntegerField(default=0, verbose_name='Bina Sayısı'),
        ),
    ]
