# Generated by Django 5.2.4 on 2025-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='img/site_settings', verbose_name='Logo')),
                ('shortcut', models.FileField(upload_to='img/site_settings', verbose_name='İkon')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.CharField(max_length=100, verbose_name='Mail')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('google_maps_link', models.CharField(max_length=1000, verbose_name='Google Maps Link')),
            ],
            options={
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
