"""
Django settings for CarbonEmissionPlatform project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure---&%9&+$j6#l(j)+!5h95_b*8xn5zpx+k82gz5cm9qg)el(_7n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'apps.web.apps.WebConfig',
    'apps.portal.apps.PortalConfig',
    'apps.site_settings.apps.SiteSettingsConfig',
    'apps.pricing.apps.PricingConfig',
    'apps.company.apps.CompanyConfig',
    'parler',
    'ckeditor',
    "django.contrib.sites",
    'allauth',
    'allauth.account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'CarbonEmissionPlatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'apps.site_settings.views.context',
            ],
        },
    },
]

WSGI_APPLICATION = 'CarbonEmissionPlatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = config.DATABASES


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

def gettext_noop(s):
    return s


LANGUAGE_CODE = 'tr'
LANGUAGES = (
    ('tr', gettext_noop('Turkish')),
    ('en', gettext_noop('English')),
)

PARLER_LANGUAGES = {
    1: (
        {'code': 'tr', },
        {'code': 'en', },
    ),
    'default': {
        'fallbacks': 'tr',
        'hide_untranslated': False,   # Default
    }
}

USE_L10N = True
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True
SITE_ID = 1

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GDAL_LIBRARY_PATH = "/opt/homebrew/opt/gdal/lib/libgdal.dylib"
GEOS_LIBRARY_PATH = '/opt/homebrew/opt/geos/lib/libgeos_c.dylib'

JAZZMIN_SETTINGS = {
    "copyright": "Portal Karbon",
    "site_title": "Portal Karbon",
    "site_header": "Portal Karbon",
    "site_brand": "Portal Karbon",
    # "site_logo": "img/isa_logo.png",
    # "login_logo": "img/isa_amblem.png",
    "show_ui_builder": True,
    "navigation_expanded": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "web": "fas fa-globe",
        "web.menuitem": "fas fa-bars",
        "web.submenu": "fas fa-ellipsis",
        "site_settings": "fas fa-gear",
        "site_settings.sitesettings": "fas fa-gear",
        "web.sliders": "fas fa-sliders",
        "web.faq": "fas fa-question",
        "web.whyuse": "fas fa-question-circle",
        "web.features": "fas fa-list",
        "web.contentblock": "fas fa-text-width",
        "pricing": "fas fa-money-bill",
        "pricing.plan": "fas fa-bag-shopping",
        "pricing.features": "fas fa-list",
        "company": "fas fa-building",
        "company.company": "fas fa-building",
        "company.facilities": "fas fa-industry",
        "company.activityarea": "fas fa-list",
        "company.sector": "fas fa-house-fire",
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_JQUERY_URL = "https://code.jquery.com/jquery-3.7.1.min.js"
# config ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': (
            ['div', 'Source', '-', 'Save', 'NewPage', 'Preview', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Print', 'SpellChecker', 'Scayt'],
            ['Undo', 'Redo', '-', 'Find', 'Replace', '-', 'SelectAll', 'RemoveFormat'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', '-', 'About', 'pbckcode'],
        ),
    }
}

AUTHENTICATION_BACKENDS = [
    'apps.portal.backends.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

LOGIN_REDIRECT_URL = '/portal'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_LOGIN_REDIRECT_URL = '/portal'  # sadece allauth için
ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'   # This will force verification
USERNAME_FIELD = 'email'


# EMAIL_BACKEND = 'django_mailjet.backends.MailjetBackend'
# MAILJET_API_KEY = '8fd28198428e04a752e7e97a3897bd14'
# MAILJET_API_SECRET = '68b69253b0628a1f65649d9a919a6c3f'
# DEFAULT_FROM_EMAIL = 'halim_turan_61@hotmail.com'

# EMAIL_HOST = 'live.smtp.mailtrap.io'
# EMAIL_HOST_USER = 'api'
# EMAIL_HOST_PASSWORD = '65883043e295a488815ae1fb5a28295b'
# EMAIL_PORT = '587'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "sandbox.smtp.mailtrap.io"
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "11f150d208fca1"
EMAIL_HOST_PASSWORD = "1631295d021069"
DEFAULT_FROM_EMAIL = "hello@demomailtrap.co"  # İstediğin bir test adresi
# https://mailtrap.io/inboxes

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"  # dev için http
